# Generated by Django 4.0.4 on 2022-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name'),
        ),
    ]
