# Generated by Django 4.0.4 on 2022-04-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0002_alter_aluno_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='productslist',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
