# Generated by Django 4.0.4 on 2022-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0003_productslist_image2_productslist_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslist',
            name='sugg_price',
        ),
        migrations.AlterField(
            model_name='productslist',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='image2',
            field=models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='image3',
            field=models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='produtos/'),
        ),
    ]
