# Generated by Django 4.0.4 on 2022-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0004_remove_productslist_sugg_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='socialmedia')),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
