# Generated by Django 4.0.4 on 2022-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0005_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='master',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
