# Generated by Django 4.0.4 on 2022-04-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0007_posts_category_alter_championship_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='belt',
            field=models.CharField(choices=[('White Belt', 'White Belt'), ('Gray/White Belt', 'Gray and White Belt'), ('Gray Belt', 'Gray Belt'), ('Gray/Black Belt', 'Gray/Black Belt'), ('Yellow/White Belt', 'Yellow/White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Yellow/Black Belt', 'Yellow/Black Belt'), ('Orange/White Belt', 'Orange/White Belt'), ('Orange Belt', 'Orange Belt'), ('Orange/Black Belt', 'Orange/Black Belt'), ('Green/White Belt', 'Green/White Belt'), ('Green Belt', 'Green Belt'), ('Green/Black Belt', 'Green/Black Belt'), ('Blue Belt', 'Blue Belt'), ('Purple Belt', 'Purple Belt'), ('Brown Belt', 'Brown Belt'), ('Black Belt', 'Black Belt')], max_length=255),
        ),
        migrations.AlterField(
            model_name='championship',
            name='category',
            field=models.CharField(choices=[('juvenile', 'Juvenil'), ('adult', 'Adulto/Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='belt',
            field=models.CharField(choices=[('White Belt', 'White Belt'), ('Gray/White Belt', 'Gray and White Belt'), ('Gray Belt', 'Gray Belt'), ('Gray/Black Belt', 'Gray/Black Belt'), ('Yellow/White Belt', 'Yellow/White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Yellow/Black Belt', 'Yellow/Black Belt'), ('Orange/White Belt', 'Orange/White Belt'), ('Orange Belt', 'Orange Belt'), ('Orange/Black Belt', 'Orange/Black Belt'), ('Green/White Belt', 'Green/White Belt'), ('Green Belt', 'Green Belt'), ('Green/Black Belt', 'Green/Black Belt'), ('Blue Belt', 'Blue Belt'), ('Purple Belt', 'Purple Belt'), ('Brown Belt', 'Brown Belt'), ('Black Belt', 'Black Belt')], max_length=255),
        ),
        migrations.AlterField(
            model_name='venda',
            name='method',
            field=models.CharField(choices=[('Credit', 'Cartão de Crédito'), ('Debit', 'Cartão de Débito'), ('Cash', 'Dinheiro'), ('Others', 'Outros')], default='Others', max_length=20),
        ),
    ]
