# Generated by Django 4.0.4 on 2022-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0008_alter_aluno_belt_alter_championship_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='belt',
            field=models.CharField(choices=[('White Belt', 'White Belt'), ('Gray/White Belt', 'Gray/White Belt'), ('Gray Belt', 'Gray Belt'), ('Gray/Black Belt', 'Gray/Black Belt'), ('Yellow/White Belt', 'Yellow/White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Yellow/Black Belt', 'Yellow/Black Belt'), ('Orange/White Belt', 'Orange/White Belt'), ('Orange Belt', 'Orange Belt'), ('Orange/Black Belt', 'Orange/Black Belt'), ('Green/White Belt', 'Green/White Belt'), ('Green Belt', 'Green Belt'), ('Green/Black Belt', 'Green/Black Belt'), ('Blue Belt', 'Blue Belt'), ('Purple Belt', 'Purple Belt'), ('Brown Belt', 'Brown Belt'), ('Black Belt', 'Black Belt')], max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='belt',
            field=models.CharField(choices=[('White Belt', 'White Belt'), ('Gray/White Belt', 'Gray/White Belt'), ('Gray Belt', 'Gray Belt'), ('Gray/Black Belt', 'Gray/Black Belt'), ('Yellow/White Belt', 'Yellow/White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Yellow/Black Belt', 'Yellow/Black Belt'), ('Orange/White Belt', 'Orange/White Belt'), ('Orange Belt', 'Orange Belt'), ('Orange/Black Belt', 'Orange/Black Belt'), ('Green/White Belt', 'Green/White Belt'), ('Green Belt', 'Green Belt'), ('Green/Black Belt', 'Green/Black Belt'), ('Blue Belt', 'Blue Belt'), ('Purple Belt', 'Purple Belt'), ('Brown Belt', 'Brown Belt'), ('Black Belt', 'Black Belt')], max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(blank=True, choices=[('newyear', 'Ano Novo'), ('xmas', 'Natal'), ('easter', 'Páscoa'), ('father', 'Dia do Pai'), ('mother', 'Dia das Mães'), ('kids', 'Dia das Crianças'), ('women', 'Dia da Mulher'), ('others', 'Outros')], default='others', max_length=20, null=True),
        ),
    ]
