# Generated by Django 4.0.4 on 2022-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0009_alter_aluno_options_alter_aluno_belt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='category',
            field=models.CharField(choices=[('kimono', 'Gi'), ('belt', 'Belt'), ('camisetas', 'T-Shirt'), ('casaco', 'Hoodie'), ('rash', 'Rash Guard'), ('short', 'Short'), ('others', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productslist',
            name='sugg_price',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque a caixa para desativar'),
        ),
    ]
