# Generated by Django 4.0.4 on 2022-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0010_productslist_category_productslist_sugg_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='sugg_price',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
