# Generated by Django 4.0.4 on 2022-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0011_alter_productslist_sugg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='sugg_price',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
