# Generated by Django 4.0.4 on 2022-04-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0012_alter_productslist_sugg_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslist',
            options={'ordering': ['item']},
        ),
    ]
