# Generated by Django 4.0.4 on 2022-04-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0013_alter_productslist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['country', 'location']},
        ),
    ]
