# Generated by Django 4.0.4 on 2022-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0015_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
    ]
