# Generated by Django 4.0.4 on 2022-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0016_alter_aluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='category',
            field=models.CharField(choices=[('pre-mirim1', 'Pré-Mirim 1'), ('pre-mirim2', 'Pré-Mirim 2'), ('pre-mirim3', 'Pré-Mirim 3'), ('mirim1', 'Mirim 1'), ('mirim2', 'Mirim 2'), ('mirim3', 'Mirim 3'), ('infantil1', 'Infantil 1'), ('infantil1', 'Infantil 2'), ('infantil1', 'Infantil 3'), ('infanto_juvenil1', 'Infanto Juvenil 1'), ('infanto_juvenil2', 'Infanto Juvenil 2'), ('infanto_juvenil3', 'Infanto Juvenil 3'), ('juvenile', 'Juvenil'), ('adult', 'Adulto/Master')], max_length=20),
        ),
    ]
