# Generated by Django 4.0.4 on 2022-04-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0017_alter_championship_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Use somente números. Código do País + Telefone', max_length=15),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacao', to='focusbjj.aluno', verbose_name='_(Aluno'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='belt',
            field=models.CharField(choices=[('White Belt', 'White Belt'), ('Gray/White Belt', 'Gray/White Belt'), ('Gray Belt', 'Gray Belt'), ('Gray/Black Belt', 'Gray/Black Belt'), ('Yellow/White Belt', 'Yellow/White Belt'), ('Yellow Belt', 'Yellow Belt'), ('Yellow/Black Belt', 'Yellow/Black Belt'), ('Orange/White Belt', 'Orange/White Belt'), ('Orange Belt', 'Orange Belt'), ('Orange/Black Belt', 'Orange/Black Belt'), ('Green/White Belt', 'Green/White Belt'), ('Green Belt', 'Green Belt'), ('Green/Black Belt', 'Green/Black Belt'), ('Blue Belt', 'Blue Belt'), ('Purple Belt', 'Purple Belt'), ('Brown Belt', 'Brown Belt'), ('Black Belt', 'Black Belt')], max_length=255, verbose_name='Faixa'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='master',
            field=models.CharField(max_length=15, null=True, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='stripe',
            field=models.CharField(choices=[('No Stripes', 'No Stripes'), ('Iº Stripe', 'Iº Stripe'), ('IIº Stripe', 'IIº Stripe'), ('IIIº Stripe', 'IIIº Stripe'), ('IVº Stripe', 'IVº Stripe'), ('-------------', '-------------'), ('Vº Stripe', 'Vº Stripe'), ('VIº Stripe', 'VIº Stripe'), ('VIIº Stripe', 'VIIº Stripe'), ('VIIIº Stripe', 'VIIIº Stripe'), ('IXº Stripe', 'IXº Stripe'), ('Xº Stripe', 'Xº Stripe'), ('XIº Stripe', 'XIº Stripe')], max_length=255, verbose_name='Grau'),
        ),
    ]
