# Generated by Django 4.0.4 on 2022-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0018_alter_customuser_phone_alter_graduation_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='category',
            field=models.CharField(choices=[('Pré-Mirim 1', 'Pré-Mirim 1'), ('Pré-Mirim 2', 'Pré-Mirim 2'), ('Pré-Mirim 3', 'Pré-Mirim 3'), ('Mirim 1', 'Mirim 1'), ('Mirim 2', 'Mirim 2'), ('Mirim 3', 'Mirim 3'), ('infantil 1', 'Infantil 1'), ('infantil 1', 'Infantil 2'), ('infantil 1', 'Infantil 3'), ('Infanto Juvenil 1', 'Infanto Juvenil 1'), ('Infanto Juvenil 2', 'Infanto Juvenil 2'), ('Infanto Juvenil 3', 'Infanto Juvenil 3'), ('Juvenil', 'Juvenil'), ('Adulto/Master', 'Adulto/Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='championship',
            name='ranking',
            field=models.CharField(choices=[('#1 place', '#1 Lugar'), ('#2 place', '#2 Lugar'), ('#3 place', '#3 Lugar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='championship',
            name='weight',
            field=models.CharField(choices=[('rooster', 'Rooster'), ('light feather', 'Light Feather'), ('feather', 'Feather'), ('light', 'Light'), ('middle', 'Middle'), ('middle heavy', 'Middle Heavy'), ('heavy', 'Heavy'), ('super_heavy', 'Super Heavy'), ('ultra heavy', 'Ultra Heavy'), ('open', 'Open')], max_length=20),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='time_stamp',
            field=models.DateTimeField(null=True, verbose_name='Data'),
        ),
    ]
