# Generated by Django 4.0.4 on 2022-04-23 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0020_alter_championship_weight_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='join_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
