# Generated by Django 4.0.4 on 2022-04-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0021_alter_aluno_join_date_alter_customuser_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focusbjj.aluno'),
        ),
    ]
