# Generated by Django 4.0.4 on 2022-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0023_aluno_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
