# Generated by Django 4.0.4 on 2022-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0024_alter_aluno_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
