# Generated by Django 4.0.4 on 2022-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusbjj', '0026_alter_aluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
