# Generated by Django 5.1.2 on 2024-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0027_aluno_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="stripe",
            field=models.CharField(
                choices=[
                    ("No Stripes", "No Stripes"),
                    ("Iº Stripe", "Iº Stripe"),
                    ("IIº Stripe", "IIº Stripe"),
                    ("IIIº Stripe", "IIIº Stripe"),
                    ("IVº Stripe", "IVº Stripe"),
                    ("Vº Stripe", "Vº Stripe"),
                    ("VIº Stripe", "VIº Stripe"),
                    ("VIIº Stripe", "VIIº Stripe"),
                    ("VIIIº Stripe", "VIIIº Stripe"),
                    ("IXº Stripe", "IXº Stripe"),
                    ("Xº Stripe", "Xº Stripe"),
                    ("XIº Stripe", "XIº Stripe"),
                ],
                default="No Stripes",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="graduation",
            name="stripe",
            field=models.CharField(
                choices=[
                    ("No Stripes", "No Stripes"),
                    ("Iº Stripe", "Iº Stripe"),
                    ("IIº Stripe", "IIº Stripe"),
                    ("IIIº Stripe", "IIIº Stripe"),
                    ("IVº Stripe", "IVº Stripe"),
                    ("Vº Stripe", "Vº Stripe"),
                    ("VIº Stripe", "VIº Stripe"),
                    ("VIIº Stripe", "VIIº Stripe"),
                    ("VIIIº Stripe", "VIIIº Stripe"),
                    ("IXº Stripe", "IXº Stripe"),
                    ("Xº Stripe", "Xº Stripe"),
                    ("XIº Stripe", "XIº Stripe"),
                ],
                max_length=255,
                verbose_name="Grau",
            ),
        ),
    ]
