# Generated by Django 5.1.2 on 2025-05-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0029_alter_aluno_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraduationRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belt",
                    models.CharField(
                        choices=[
                            ("White Belt", "White Belt"),
                            ("Gray/White Belt", "Gray/White Belt"),
                            ("Gray Belt", "Gray Belt"),
                            ("Gray/Black Belt", "Gray/Black Belt"),
                            ("Yellow/White Belt", "Yellow/White Belt"),
                            ("Yellow Belt", "Yellow Belt"),
                            ("Yellow/Black Belt", "Yellow/Black Belt"),
                            ("Orange/White Belt", "Orange/White Belt"),
                            ("Orange Belt", "Orange Belt"),
                            ("Orange/Black Belt", "Orange/Black Belt"),
                            ("Green/White Belt", "Green/White Belt"),
                            ("Green Belt", "Green Belt"),
                            ("Green/Black Belt", "Green/Black Belt"),
                            ("Blue Belt", "Blue Belt"),
                            ("Purple Belt", "Purple Belt"),
                            ("Brown Belt", "Brown Belt"),
                            ("Black Belt", "Black Belt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stripes",
                    models.CharField(
                        choices=[
                            ("No Stripes", "No Stripes"),
                            ("Iº Stripe", "Iº Stripe"),
                            ("IIº Stripe", "IIº Stripe"),
                            ("IIIº Stripe", "IIIº Stripe"),
                            ("IVº Stripe", "IVº Stripe"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "required_classes",
                    models.PositiveIntegerField(
                        help_text="Number of classes required for promotion"
                    ),
                ),
                (
                    "is_adult",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this requirement applies to adults or kids",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional requirements or notes",
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Graduation Requirement",
                "verbose_name_plural": "Graduation Requirements",
                "ordering": ["is_adult", "belt", "stripes"],
                "unique_together": {("belt", "stripes", "is_adult")},
            },
        ),
    ]
