# Generated by Django 5.1.2 on 2025-05-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0030_graduationrequirement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graduationrequirement",
            options={
                "ordering": ["belt", "stripes"],
                "verbose_name": "Graduation Requirement",
                "verbose_name_plural": "Graduation Requirements",
            },
        ),
        migrations.AlterUniqueTogether(
            name="graduationrequirement", unique_together={("belt", "stripes")},
        ),
        migrations.RemoveField(model_name="graduationrequirement", name="description",),
        migrations.RemoveField(model_name="graduationrequirement", name="is_adult",),
    ]
