# Generated by Django 5.1.2 on 2025-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0031_alter_graduationrequirement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="stripe",
            field=models.CharField(
                choices=[
                    ("No Stripes", "No Stripes"),
                    ("Iº Stripe", "Iº Stripe"),
                    ("IIº Stripe", "IIº Stripe"),
                    ("IIIº Stripe", "IIIº Stripe"),
                    ("IVº Stripe", "IVº Stripe"),
                ],
                default="No Stripes",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="graduation",
            name="stripe",
            field=models.CharField(
                choices=[
                    ("No Stripes", "No Stripes"),
                    ("Iº Stripe", "Iº Stripe"),
                    ("IIº Stripe", "IIº Stripe"),
                    ("IIIº Stripe", "IIIº Stripe"),
                    ("IVº Stripe", "IVº Stripe"),
                ],
                max_length=255,
                verbose_name="Grau",
            ),
        ),
        migrations.AlterField(
            model_name="graduationrequirement",
            name="belt",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Gray/White", "Gray/White"),
                    ("Gray", "Gray"),
                    ("Gray/Black", "Gray/Black"),
                    ("Yellow/White", "Yellow/White"),
                    ("Yellow", "Yellow"),
                    ("Yellow/Black", "Yellow/Black"),
                    ("Orange/White", "Orange/White"),
                    ("Orange", "Orange"),
                    ("Orange/Black", "Orange/Black"),
                    ("Green/White", "Green/White"),
                    ("Green", "Green"),
                    ("Green/Black", "Green/Black"),
                    ("Blue", "Blue"),
                    ("Purple", "Purple"),
                    ("Brown", "Brown"),
                    ("Black", "Black"),
                ],
                max_length=20,
            ),
        ),
    ]
