# Generated by Django 5.1.2 on 2025-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0032_alter_aluno_stripe_alter_graduation_stripe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="belt",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Gray/White", "Gray/White"),
                    ("Gray", "Gray"),
                    ("Gray/Black", "Gray/Black"),
                    ("Yellow/White", "Yellow/White"),
                    ("Yellow", "Yellow"),
                    ("Yellow/Black", "Yellow/Black"),
                    ("Orange/White", "Orange/White"),
                    ("Orange", "Orange"),
                    ("Orange/Black", "Orange/Black"),
                    ("Green/White", "Green/White"),
                    ("Green", "Green"),
                    ("Green/Black", "Green/Black"),
                    ("Blue", "Blue"),
                    ("Purple", "Purple"),
                    ("Brown", "Brown"),
                    ("Black", "Black"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="graduation",
            name="belt",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Gray/White", "Gray/White"),
                    ("Gray", "Gray"),
                    ("Gray/Black", "Gray/Black"),
                    ("Yellow/White", "Yellow/White"),
                    ("Yellow", "Yellow"),
                    ("Yellow/Black", "Yellow/Black"),
                    ("Orange/White", "Orange/White"),
                    ("Orange", "Orange"),
                    ("Orange/Black", "Orange/Black"),
                    ("Green/White", "Green/White"),
                    ("Green", "Green"),
                    ("Green/Black", "Green/Black"),
                    ("Blue", "Blue"),
                    ("Purple", "Purple"),
                    ("Brown", "Brown"),
                    ("Black", "Black"),
                ],
                max_length=255,
                verbose_name="Faixa",
            ),
        ),
    ]
