# Generated by Django 5.1.2 on 2025-05-02 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0033_alter_aluno_belt_alter_graduation_belt"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "related_to_graduation",
                    models.BooleanField(
                        default=False,
                        help_text="Is this feedback related to a graduation?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_graduation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="focusbjj.graduation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="focusbjj.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Feedback",
                "verbose_name_plural": "Student Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
