# Generated by Django 5.1.2 on 2025-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0034_studentfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeedback",
            name="professor_name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for the professor giving feedback",
                max_length=100,
            ),
        ),
    ]
