# Generated by Django 5.1.2 on 2025-06-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("focusbjj", "0035_studentfeedback_professor_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="championship", name="athlete",),
        migrations.DeleteModel(name="Posts",),
        migrations.RemoveField(model_name="product", name="product",),
        migrations.RemoveField(model_name="product", name="venda",),
        migrations.RemoveField(model_name="venda", name="aluno",),
        migrations.RemoveField(model_name="venda", name="unidade",),
        migrations.DeleteModel(name="Championship",),
        migrations.DeleteModel(name="ProductsList",),
        migrations.DeleteModel(name="Product",),
        migrations.DeleteModel(name="Venda",),
    ]
